language: r
sudo: false
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files

before_script:
  - chmod +x ./deployment/_build.sh
  - chmod +x ./deployment/_deploy.sh

script:
  - ./deployment/_build.sh
  - ./deployment/_deploy.sh
